-- Run this in Supabase SQL Editor to add scrape_results and RLS (if not already set up).
-- Your existing tables: users, links (with user_id -> users.id).

-- Ensure links has a primary key on id (required for scrape_results foreign key)
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.links'::regclass and conname = 'links_pkey'
  ) then
    alter table public.links add constraint links_pkey primary key (id);
  end if;
end $$;

-- Scrape results: one row per scrape per link
create table if not exists public.scrape_results (
  id bigint generated by default as identity primary key,
  link_id bigint not null references public.links(id) on delete cascade,
  scraped_at timestamptz not null default now(),
  job_titles text[] not null default '{}'
);

-- Optional: unique email on users for lookups (only if not already there)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'users_email_key'
  ) then
    alter table public.users add constraint users_email_key unique (email);
  end if;
end $$;

-- RLS: enable and policies (adjust as needed for your project)
alter table public.users enable row level security;
alter table public.links enable row level security;
alter table public.scrape_results enable row level security;

-- Users: allow insert when email matches auth (for signup sync)
create policy "Users insert own" on public.users
  for insert with check (auth.jwt()->>'email' = email);

create policy "Users select own" on public.users
  for select using (auth.jwt()->>'email' = email);

-- Links: user can only access their own links
create policy "Links select own" on public.links
  for select using (
    user_id in (select id from public.users where email = auth.jwt()->>'email')
  );
create policy "Links insert own" on public.links
  for insert with check (
    user_id in (select id from public.users where email = auth.jwt()->>'email')
  );
create policy "Links update own" on public.links
  for update using (
    user_id in (select id from public.users where email = auth.jwt()->>'email')
  );
create policy "Links delete own" on public.links
  for delete using (
    user_id in (select id from public.users where email = auth.jwt()->>'email')
  );

-- Scrape results: user can only access results for their links
create policy "Scrape results select own" on public.scrape_results
  for select using (
    link_id in (
      select id from public.links
      where user_id in (select id from public.users where email = auth.jwt()->>'email')
    )
  );
create policy "Scrape results insert own" on public.scrape_results
  for insert with check (
    link_id in (
      select id from public.links
      where user_id in (select id from public.users where email = auth.jwt()->>'email')
    )
  );
create policy "Scrape results delete own" on public.scrape_results
  for delete using (
    link_id in (
      select id from public.links
      where user_id in (select id from public.users where email = auth.jwt()->>'email')
    )
  );
